---
# Network Interfaces
template_interfaces:
  - device: eth0
    bootproto: static
    ip: "{{ ansible_host }}"
    gateway: "10.0.0.1"
    netmask: "255.255.254.0"
    dns_search: "example.domain.com"
    dns_nameservers: "8.8.4.4"
